global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.Primitives;
global using Avalonia.Data;
global using Avalonia.Input;
global using Avalonia.Layout;
global using Avalonia.Media;
global using Avalonia.Metadata;
global using CommunityToolkit.Mvvm.ComponentModel;
global using static Euterpe.Localization.XAMLLiteral;
global using static Euterpe.Shared.BuildInfo;
