global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Euterpe.Generators.Extensions;
global using Euterpe.Generators.StringBuilders;
global using static Euterpe.Generators.BuildInfo;
global using static Euterpe.Generators.SourceGenerationTexts;
global using static Euterpe.Generators.SourceGeneratorHelper;