global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using AsyncAwaitBestPractices;
global using Autofac;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Data.Converters;
global using Avalonia.Threading;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Downloader;
global using DynamicData;
global using Euterpe.Abstractions;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Logger;
global using Euterpe.Extensions;
global using Euterpe.Localization;
global using Euterpe.Models;
global using Euterpe.Models.Enums;
global using Euterpe.Models.Games;
global using Euterpe.Services;
global using Euterpe.Shared;
global using Euterpe.Shared.Attributes;
global using Euterpe.Shared.Extensions;
global using DotNext.Threading;
global using Euterpe.Controls.Models;
global using Euterpe.ViewModels;
global using Euterpe.ViewModels.Components;
global using Euterpe.ViewModels.Components.Wizard;
global using Euterpe.ViewModels.Pages;
global using Euterpe.ViewModels.Panels.Charting;
global using Euterpe.ViewModels.Panels.Logging;
global using Euterpe.ViewModels.Panels.Modding;
global using Euterpe.ViewModels.Panels.Setting;
global using Euterpe.ViewModels.Windows;
global using Euterpe.Views;
global using Euterpe.Views.Components;
global using Euterpe.Views.Components.Wizard;
global using Euterpe.Views.Pages;
global using Euterpe.Views.Panels.Charting;
global using Euterpe.Views.Panels.Logging;
global using Euterpe.Views.Panels.Modding;
global using Euterpe.Views.Panels.Setting;
global using Euterpe.Views.Windows;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Logging;
global using R3;
global using Ursa.Controls;
global using ZLogger;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using static Euterpe.Localization.XAMLLiteral;
global using static Euterpe.Shared.BuildInfo;
global using static Euterpe.Shared.PathConstants;