global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Autofac;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Data.Converters;
global using Avalonia.Threading;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Downloader;
global using DynamicData;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Logging;
global using Euterpe.Abstractions;
global using Euterpe.Common;
global using Euterpe.Common.Extensions;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Logger;
global using Euterpe.Core.Utils;
global using Euterpe.Extensions;
global using Euterpe.Localization;
global using Euterpe.Models;
global using Euterpe.Models.Controls;
global using Euterpe.Models.Enums;
global using Euterpe.Services;
global using Euterpe.ViewModels;
global using Euterpe.ViewModels.Components;
global using Euterpe.ViewModels.Pages;
global using Euterpe.ViewModels.Panels.Charting;
global using Euterpe.ViewModels.Panels.Logging;
global using Euterpe.ViewModels.Panels.Modding;
global using Euterpe.ViewModels.Panels.Setting;
global using Euterpe.Views;
global using Euterpe.Views.Components;
global using Euterpe.Views.Pages;
global using Euterpe.Views.Panels.Charting;
global using Euterpe.Views.Panels.Logging;
global using Euterpe.Views.Panels.Modding;
global using Euterpe.Views.Panels.Setting;
global using R3;
global using Ursa.Controls;
global using ZLogger;
global using static Euterpe.Common.BuildInfo;
global using static Euterpe.Common.GlobalConstants;
global using static Euterpe.Common.PageNames;
global using static Euterpe.Common.PathConstants;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using static Euterpe.Localization.XAMLLiteral;