global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using AsyncAwaitBestPractices;
global using Autofac;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Data.Converters;
global using Avalonia.Threading;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Downloader;
global using DynamicData;
global using Euterpe.Abstractions;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Logger;
global using Euterpe.Extensions;
global using Euterpe.Localization;
global using Euterpe.Models;
global using Euterpe.Models.Auth;
global using Euterpe.Models.Charts;
global using Euterpe.Models.Common;
global using Euterpe.Models.Games;
global using Euterpe.Models.Mods;
global using Euterpe.Models.Setup;
global using Euterpe.Models.Wizard;
global using Euterpe.Services;
global using Euterpe.Shared;
global using Euterpe.Shared.Attributes;
global using Euterpe.Shared.Extensions;
global using DotNext.Threading;
global using Euterpe.Controls.Models;
global using Euterpe.Features.Charting;
global using Euterpe.Features.Home;
global using Euterpe.Features.Logging;
global using Euterpe.Features.Modding;
global using Euterpe.Features.Setting;
global using Euterpe.Features.Setup;
global using Euterpe.Features.Wizard;
global using Euterpe.Mvvm;
global using Euterpe.Shell;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Logging;
global using R3;
global using Ursa.Controls;
global using ZLogger;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using static Euterpe.Localization.XAMLLiteral;
global using static Euterpe.Shared.BuildInfo;
global using static Euterpe.Shared.PathConstants;