global using System.Text.Json.Serialization;
global using CommunityToolkit.Mvvm.ComponentModel;
global using Euterpe.Models.Auth;
global using Euterpe.Models.Charts;
global using Euterpe.Models.Common;
global using Euterpe.Models.Games;
global using Euterpe.Models.Mods;
global using Euterpe.Models.Setup;
global using Euterpe.Models.Wizard;
global using Euterpe.Shared;
global using Euterpe.Shared.Extensions;
global using JetBrains.Annotations;
global using static Euterpe.Localization.XAMLLiteral;
global using static Euterpe.Shared.GitHubConstants;
global using static Euterpe.Shared.PathConstants;
