<Project>
    <Import Project="NativeAot.props"/>

    <PropertyGroup>
        <DefineConstants Condition="'$(IsPublishing)' == 'true'">$(DefineConstants);PUBLISH</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <DebuggerSupport>false</DebuggerSupport>
    </PropertyGroup>

    <Target Name="Exclude Package Pdbs" AfterTargets="ComputeFilesToPublish">
        <ItemGroup>
            <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'"/>
        </ItemGroup>
    </Target>

    <Target Name="Copy Builds" AfterTargets="Publish">
        <ItemGroup>
            <_PublishedFiles Include="$(PublishDir)*.*"/>
        </ItemGroup>

        <Copy SourceFiles="@(_PublishedFiles)" DestinationFolder="$(ArtifactsPath)output" SkipUnchangedFiles="true"/>
    </Target>
</Project>
