<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="Euterpe.Shared.targets"/>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Euterpe.CodeAnalysis\Euterpe.CodeAnalysis.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
