global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using Autofac;
global using Avalonia.Controls;
global using Downloader;
global using DynamicData;
global using Euterpe.Abstractions;
global using Euterpe.Contracts.GitHub;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Logger;
global using Euterpe.Core.Proxies;
global using Euterpe.Core.Utils;
global using Euterpe.Models;
global using Euterpe.Models.Enums;
global using Euterpe.Shared;
global using Euterpe.Shared.Attributes;
global using Euterpe.Shared.Extensions;
global using Euterpe.Shared.Primitives;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Semver;
global using Ursa.Controls;
global using ZLogger;
global using static Euterpe.Core.GitHubResources;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using static Euterpe.Shared.BuildInfo;
global using static Euterpe.Shared.GitHubConstants;