global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using Autofac;
global using Downloader;
global using DynamicData;
global using Euterpe.Abstractions;
global using Euterpe.Contracts;
global using Euterpe.Contracts.GitHub;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Http.Clients;
global using Euterpe.Core.Logger;
global using Euterpe.Core.Proxies;
global using Euterpe.Core.Utils;
global using Euterpe.Localization;
global using Euterpe.Models;
global using Euterpe.Models.Auth;
global using Euterpe.Models.Charts;
global using Euterpe.Models.Common;
global using Euterpe.Models.Games;
global using Euterpe.Models.Migrations;
global using Euterpe.Models.Mods;
global using Euterpe.Models.Playback;
global using Euterpe.Models.Setup;
global using Euterpe.Models.Wizard;
global using Euterpe.Shared;
global using Euterpe.Shared.Attributes;
global using Euterpe.Shared.Extensions;
global using DotNext.Threading;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Semver;
global using ZLogger;
global using static Euterpe.Core.GitHubResources;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using static Euterpe.Shared.BuildInfo;
global using static Euterpe.Shared.GitHubConstants;
global using static Euterpe.Shared.PathConstants;
