global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using Autofac;
global using Avalonia.Controls;
global using Downloader;
global using DynamicData;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Euterpe.Abstractions;
global using Euterpe.Common.Attributes;
global using Euterpe.Common.Extensions;
global using Euterpe.Core.Extensions;
global using Euterpe.Core.Logger;
global using Euterpe.Core.Proxies;
global using Euterpe.Core.Utils;
global using Euterpe.Models;
global using Euterpe.Models.Enums;
global using Euterpe.Models.GitHub;
global using R3;
global using Semver;
global using Ursa.Controls;
global using ZLogger;
global using static Euterpe.Common.ApiConstants;
global using static Euterpe.Common.BuildInfo;
global using static Euterpe.Common.GitHubConstants;
global using static Euterpe.Common.GitHubResources;
global using static Euterpe.Common.GlobalConstants;
global using static Euterpe.Core.Utils.DesktopUtils;
global using static Euterpe.Localization.Interaction;
global using MultiThreadDownloader = Downloader.DownloadService;