<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Euterpe.Contracts\Euterpe.Contracts.csproj"/>
        <ProjectReference Include="..\Euterpe.Models\Euterpe.Models.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Downloader"/>
        <PackageReference Include="DynamicData"/>
        <PackageReference Include="Irihi.Ursa"/>
    </ItemGroup>

</Project>
