//HintName: LazyProxyExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Core.Extensions;

public static class LazyProxyExtensions
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.LazyProxyGenerator", "1.0.0")]
    public static void RegisterLazyProxies(this ContainerBuilder builder)
    {
        builder.RegisterType<Sample.GreeterProxy>().PropertiesAutowired().SingleInstance();
    }
}
