//HintName: GreeterProxy.Proxy.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Sample;

partial class GreeterProxy
{
    public required Lazy<Greeter> Greeter { get; init; }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.LazyProxyGenerator", "1.0.0")]
    public string Greet(string name) => Greeter.Value.Greet(name);

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.LazyProxyGenerator", "1.0.0")]
    public int Count => Greeter.Value.Count;

}
