//HintName: SettingsViewViewModel.Routes.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


using System.Collections.Frozen;

namespace Sample.ViewModels;

partial class SettingsViewViewModel
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    [global::JetBrains.Annotations.UsedImplicitly]
    public required global::Euterpe.Services.NavigationService NavigationService { get; init; }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    public override global::System.Collections.Generic.IReadOnlyList<global::Euterpe.Controls.Models.NavItem> NavItems { get; } =
    [
        new(global::Euterpe.Localization.XAMLLiteral.General, "/settings/general"),
        new(global::Euterpe.Localization.XAMLLiteral.Advanced, "/settings/advanced"),
    ];

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    private static readonly FrozenDictionary<string, global::System.Func<global::Euterpe.Services.NavigationService, global::Avalonia.Controls.Control>> RouteLookup =
        new global::System.Collections.Generic.Dictionary<string, global::System.Func<global::Euterpe.Services.NavigationService, global::Avalonia.Controls.Control>>
        {
            ["/settings/general"] = static ns => ns.NavigateTo<global::Sample.Views.GeneralSettingsView>(),
            ["/settings/advanced"] = static ns => ns.NavigateTo<global::Sample.Views.AdvancedSettingsView>(),
        }.ToFrozenDictionary();

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.RouteGenerator", "1.0.0")]
    protected override global::Avalonia.Controls.Control ResolveRoute(string route)
        => RouteLookup[route](NavigationService);
}
