//HintName: ServiceExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Euterpe source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable


namespace Euterpe.Extensions;

partial class ServiceExtensions
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.ServiceExtensionsGenerator", "1.0.0")]
    public static void RegisterAppViewsAndViewModels(this ContainerBuilder builder)
    {
        builder.RegisterType<global::Euterpe.ViewModels.AppViewModel>().PropertiesAutowired().SingleInstance();

		builder.RegisterType<HomeViewViewModel>().PropertiesAutowired().SingleInstance();
		builder.Register<HomeView>(ctx => new HomeView { DataContext = ctx.Resolve<HomeViewViewModel>() }).SingleInstance();

		builder.RegisterType<SettingsViewViewModel>().PropertiesAutowired().SingleInstance();
		builder.Register<SettingsView>(ctx => new SettingsView { DataContext = ctx.Resolve<SettingsViewViewModel>() }).SingleInstance();

    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.ServiceExtensionsGenerator", "1.0.0")]
    public static void RegisterPerGameViews(this ContainerBuilder builder)
    {
        builder.Register<GameDetailView>(_ =>
        {
            var view = new GameDetailView();
            global::Euterpe.IocContainer.GameScopeObservable.Subscribe(scope =>
            {
                var viewModel = scope.Resolve<GameDetailViewViewModel>();
                view.DataContext = viewModel;
                viewModel.InitializeAsync().SafeFireAndForget();
            });
            return view;
        }).SingleInstance();

        builder.Register<GameSettingsView>(_ =>
        {
            var view = new GameSettingsView();
            global::Euterpe.IocContainer.GameScopeObservable.Subscribe(scope =>
            {
                var viewModel = scope.Resolve<GameSettingsViewViewModel>();
                view.DataContext = viewModel;
                viewModel.InitializeAsync().SafeFireAndForget();
            });
            return view;
        }).SingleInstance();

    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Euterpe.SourceGenerators.ServiceExtensionsGenerator", "1.0.0")]
    public static void RegisterPerGameViewModels(this ContainerBuilder builder)
    {
		builder.RegisterType<GameDetailViewViewModel>().PropertiesAutowired().InstancePerLifetimeScope();
		builder.RegisterType<GameSettingsViewViewModel>().PropertiesAutowired().InstancePerLifetimeScope();
    }
}
