<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
        <PackageReference Include="NetArchTest.eNhancedEdition"/>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Mocks"/>
        <PackageReference Include="TUnit.Mocks.Http"/>
        <PackageReference Include="Verify.TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Euterpe.Core\Euterpe.Core.csproj"/>
    </ItemGroup>

</Project>
