<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAotCompatible>false</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="NetArchTest.eNhancedEdition"/>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="TUnit.Mocks"/>
        <PackageReference Include="TUnit.Mocks.Http"/>
        <PackageReference Include="TUnit.Mocks.Logging"/>
        <PackageReference Include="Verify.TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Euterpe\Euterpe.csproj"/>
        <ProjectReference Include="..\..\src\Euterpe.Core\Euterpe.Core.csproj"/>
    </ItemGroup>

</Project>
