global using Euterpe.Abstractions;
global using Euterpe.Core;
global using Euterpe.Models;
global using Euterpe.Models.Auth;
global using Euterpe.Models.Charts;
global using Euterpe.Models.Common;
global using Euterpe.Models.Games;
global using Euterpe.Models.Mods;
global using Euterpe.Models.Setup;
global using Euterpe.Models.Wizard;
global using Euterpe.Shared;
global using Euterpe.Tests.Comparers;
global using JetBrains.Annotations;
global using TUnit.Assertions.Enums;
global using static Euterpe.Shared.BuildInfo;