name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare GitHub draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Validate release tag
        run: git grep -F "<Version>${GITHUB_REF_NAME}</Version>" -- Directory.Build.props

      - name: Create GitHub draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: true

  stage:
    name: Stage (${{ matrix.rid }})
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: linux-x64
            os: ubuntu-latest
          - rid: linux-arm64
            os: ubuntu-latest
          - rid: win-x64
            os: windows-latest
          - rid: win-arm64
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build --report-trx

      - name: Restore tools
        run: dotnet tool restore

      - name: Stage release
        env:
          EUTERPE_API_KEY: ${{ secrets.EUTERPE_API_KEY }}
        run: >
          dotnet run
          --project build/Euterpe.Releaser/Euterpe.Releaser.csproj
          -c Release
          --no-build
          -- stage
          --rid "${{ matrix.rid }}"

      - name: Upload installer to GitHub draft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          fail_on_unmatched_files: false
          files: |
            artifacts/releases/${{ matrix.rid }}-${{ contains(github.ref_name, '-') && 'beta' || 'stable' }}/*.exe
            artifacts/releases/${{ matrix.rid }}-${{ contains(github.ref_name, '-') && 'beta' || 'stable' }}/*.AppImage

  publish:
    name: Publish release
    needs: stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Publish staged release
        env:
          EUTERPE_API_KEY: ${{ secrets.EUTERPE_API_KEY }}
        run: >
          dotnet run
          --project build/Euterpe.Releaser/Euterpe.Releaser.csproj
          -c Release
          -- publish

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
